### ISSUE TITLE
`PYAPP_PROJECT_VERSION` default to latest

### ISSUE THREAD

**Issue by T-256** [ofek/pyapp#71]
one less env set

**Comment by ofek** [comment]
I want the version to be explicit and also I don't want to parse any index endpoint at build time for now

**Comment by RhetTbull** [comment]
First, thank you for building PyApp! It really is an amazing tool and I'm looking to move all my Python CLIs to PyApp. I currently maintain several packages (primarily for macOS) where I distribute binaries with pyinstaller and looking to move to PyApp mainly for the `self update` feature which is amazing.

Understand you've closed this (so I'm interpreting that as a "will not implement" for now) but I too think this would be very useful. I'm looking to switch to PyApp and currently doing so for [this](https://github.com/RhetTbull/makelive) project as a test run. Given how PyApp works it seems quite feasible that the PyApp binary could be built one time and distributed without having to rebuild it every time the python package changes if PyApp just grabbed the latest by default. (And maybe an option to pin a specific version at first run). As it is I will now need to build PyApp with each new release and this cannot be done until after the release is distributed to PyPI (since the version will be in valid until then) but the binary itself will not change with exception of which version of the package is being downloaded.
